### ISSUE TITLE
Error while running debot

### ISSUE THREAD

**Issue by ilyar** [Strafi/debot-embedding#1]
```log
Error while running debot:  { code: 802,
  message: 'Debot fetch failed: failed to parse abi: invalid type: integer `7`, expected struct AbiContract at line 1 column 1',
  data: { core_version: '1.25.0' } }
```

`0:46c5c13ce11cad4a05b399dda34e75e0806c47d0c422871d1a914f3dfd3e0131` devnet

![image](https://user-images.githubusercontent.com/761285/152372662-ab11dcc0-a29e-427a-9366-2b624712e45f.png)
https://replit.com/@ilyar/DeBot#index.html

**Comment by Strafi** [comment]
Fixed in v0.2.0
